Implement remaining time option
sll552/DiscordBee pull request #45
Opened 2020-09-19 02:19 UTC by pazuzu156

Added a remaining time display option in the settings (as checkbox)

Got around do pushing my changes a little earlier. Here's what I have, and images to show the changes
![Discord_SgRQStvi7y](https://user-images.githubusercontent.com/647577/93657025-d9d65a80-f9fc-11ea-91ff-d2fce526f9e5.png)  
![MusicBee_scHHpSFNTN](https://user-images.githubusercontent.com/647577/93657028-e064d200-f9fc-11ea-97ed-8320c73da29c.png)  
![Discord_csUZ71e1W3](https://user-images.githubusercontent.com/647577/93657030-e3f85900-f9fc-11ea-900b-6bbbb0b10202.png)

2020-09-19 15:34 UTC, AKASGaming commented
How do I update DiscordBee to this?

2020-09-19 16:09 UTC, pazuzu156 commented
Just replace your mb_DiscordBee.dll file with the one in this .zip archive. Keep in mind it's not an "official" build so I'd update once sl522 makes an update with the changes. This should work until then  
[mb_DiscordBee.zip](https://github.com/sll552/DiscordBee/files/5250143/mb_DiscordBee.zip)

2020-09-19 16:11 UTC, AKASGaming commented
![image](https://user-images.githubusercontent.com/25405047/93671471-e5f80180-fa68-11ea-9d63-11cdecae6744.png)
?

2020-09-19 17:27 UTC, pazuzu156 commented
is that error from musicbee or what you extracted with?

2020-09-19 18:07 UTC, AKASGaming commented
First I tried it without extracting and it gave me an error
Then I tried extracting then added it and it gave me that error.
I did completely delete the old DiscordBee before doing that, too.

2020-09-19 20:10 UTC, pazuzu156 commented
That's odd, I didn't touch anything as far as settings are concerned other than adding the setting for elapsed time switch. Let sll552 review the PR and if they decide to merge, wait for a new build. Could always download the code from my fork and build it in the meantime

2020-09-19 20:16 UTC, sll552 commented
LGTM, but please change the default value, so that there is no change in behavior when people update to a new plugin version

2020-09-19 20:24 UTC, pazuzu156 commented
@sll552 I'm guessing that's what you wanted?

2020-09-19 20:42 UTC, sll552 requested changes

2020-09-19 20:42 UTC, sll552 commented on Settings.cs
> +          _showRemainingTime = false;
This would set the value to false everytime the user tries to change it, so please remove this change. The correct way is to change the get function.

2020-09-19 20:42 UTC, sll552 commented on Settings.cs
> +      get => !_showRemainingTime.HasValue || _showRemainingTime.Value;
```suggestion
      get => _showRemainingTime.HasValue && _showRemainingTime.Value;
```

2020-09-19 20:46 UTC, sll552 commented
And after applying the changes please squash your commits into one so the history is kept clean

2020-09-19 21:01 UTC, pazuzu156 commented
Changes made and commits squashed

2020-09-19 21:18 UTC, merged

2020-09-20 07:29 UTC, Rings4 commented
When are you going to release this as a release?

2020-09-21 08:48 UTC, sll552 commented
I want to fix and update a few things before releasing, expect a few days.

2020-09-26 15:13 UTC, sll552 commented
Released as 1.4.0 https://github.com/sll552/DiscordBee/releases/tag/v1.4.0